### ISSUE TITLE
App crashing when entering groups id that doesn't exist

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#55]
1. Create a new group
2. Change any digit on the groups id on the url bar
3. Press enter
4. App crashes
You could use the id below
/groups/55521d1f7ac86b72138fff12/members/list

**Comment by mujuni88** [comment]
Users/joebm08/GitHub/projects/sportsscheduler/app/custom_objects/MyResponse.js:28
	this.error.devMessage.push(errObj.devMessage);
	                                 ^
TypeError: Cannot read property 'devMessage' of undefined
    at MyResponse.addMessages (/Users/joebm08/GitHub/projects/sportsscheduler/app/custom_objects/MyResponse.js:28:35)
    at /Users/joebm08/GitHub/projects/sportsscheduler/app/controllers/users/groups/groups.server.controller.js:124:15
    at Promise.<anonymous> (/Users/joebm08/GitHub/projects/sportsscheduler/app/custom_objects/Helper.js:84:17)
    at Promise.<anonymous> (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/lib/promise.js:108:23)
    at Promise.<anonymous> (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
[nodemon] app crashed - waiting for file changes before starting...
