### ISSUE TITLE
Error while joining group

### ISSUE THREAD

**Issue by mujuni88** [mujuni88/sportsscheduler#62]
Hey @tqg5,
I encountered the following error while joining a group. 

validate created groups: 555a36e91011cb4b943a9983,555bad4403b4770000051a11
validate joined groups: 555b96ad03b4770000051a0f,555b96ad03b4770000051a0f
error: ValidationError: joinedGroups.duplicate
stuff:  joinedGroups.duplicate
saved successfully

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/express/lib/response.js:592:10)
    at ServerResponse.send (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/express/lib/response.js:144:12)
    at ServerResponse.json (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/express/lib/response.js:233:15)
    at Object.Helper.output (/Users/joebm08/GitHub/projects/sportsscheduler/app/custom_objects/Helper.js:299:21)
    at /Users/joebm08/GitHub/projects/sportsscheduler/app/controllers/users/users.profile.server.controller.js:133:12
    at handleError (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/hooks/hooks.js:92:18)
    at _next (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/hooks/hooks.js:34:22)
    at fnWrapper (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)
    at complete (/Users/joebm08/GitHub/projects/sportsscheduler/node_modules/mongoose/lib/document.js:977:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by tqg5** [comment]
What steps did you do to cause this? 

@mujuni88

**Comment by tqg5** [comment]
I haven't been able to reproduce this in my environment. What steps did you take to cause this? @mujuni88
